/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as ApplySlugRouteImport } from './routes/apply.$slug'
import { Route as MarketSlugRouteImport } from './routes/market.$slug'
import { Route as OrganizerLayoutRouteImport } from './routes/organizer/_layout'
import { Route as StoreVendorIdRouteImport } from './routes/store.$vendorId'
import { Route as VendorLayoutRouteImport } from './routes/vendor/_layout'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as AdminLayoutOrganizationsRouteImport } from './routes/admin/_layout/organizations'
import { Route as OrganizerLayoutIndexRouteImport } from './routes/organizer/_layout/index'
import { Route as OrganizerLayoutAnalyticsRouteImport } from './routes/organizer/_layout/analytics'
import { Route as OrganizerLayoutCommunicationsRouteImport } from './routes/organizer/_layout/communications'
import { Route as OrganizerLayoutComplianceRouteImport } from './routes/organizer/_layout/compliance'
import { Route as OrganizerLayoutOrdersRouteImport } from './routes/organizer/_layout/orders'
import { Route as OrganizerLayoutPaymentsRouteImport } from './routes/organizer/_layout/payments'
import { Route as OrganizerLayoutScheduleRouteImport } from './routes/organizer/_layout/schedule'
import { Route as OrganizerLayoutSettingsRouteImport } from './routes/organizer/_layout/settings'
import { Route as OrganizerLayoutVendorsRouteImport } from './routes/organizer/_layout/vendors'
import { Route as VendorLayoutIndexRouteImport } from './routes/vendor/_layout/index'
import { Route as VendorLayoutDocumentsRouteImport } from './routes/vendor/_layout/documents'
import { Route as VendorLayoutProductsRouteImport } from './routes/vendor/_layout/products'
import { Route as VendorLayoutProfileRouteImport } from './routes/vendor/_layout/profile'
import { Route as VendorClaimVendorIdRouteImport } from './routes/vendor/claim.$vendorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplySlugRoute = ApplySlugRouteImport.update({
  id: '/apply/$slug',
  path: '/apply/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketSlugRoute = MarketSlugRouteImport.update({
  id: '/market/$slug',
  path: '/market/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerLayoutRoute = OrganizerLayoutRouteImport.update({
  id: '/organizer/_layout',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreVendorIdRoute = StoreVendorIdRouteImport.update({
  id: '/store/$vendorId',
  path: '/store/$vendorId',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorLayoutRoute = VendorLayoutRouteImport.update({
  id: '/vendor/_layout',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutOrganizationsRoute =
  AdminLayoutOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const OrganizerLayoutIndexRoute = OrganizerLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizerLayoutRoute,
} as any)
const OrganizerLayoutAnalyticsRoute =
  OrganizerLayoutAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => OrganizerLayoutRoute,
  } as any)
const OrganizerLayoutCommunicationsRoute =
  OrganizerLayoutCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => OrganizerLayoutRoute,
  } as any)
const OrganizerLayoutComplianceRoute =
  OrganizerLayoutComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => OrganizerLayoutRoute,
  } as any)
const OrganizerLayoutOrdersRoute = OrganizerLayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => OrganizerLayoutRoute,
} as any)
const OrganizerLayoutPaymentsRoute = OrganizerLayoutPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => OrganizerLayoutRoute,
} as any)
const OrganizerLayoutScheduleRoute = OrganizerLayoutScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => OrganizerLayoutRoute,
} as any)
const OrganizerLayoutSettingsRoute = OrganizerLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrganizerLayoutRoute,
} as any)
const OrganizerLayoutVendorsRoute = OrganizerLayoutVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => OrganizerLayoutRoute,
} as any)
const VendorLayoutIndexRoute = VendorLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorLayoutRoute,
} as any)
const VendorLayoutDocumentsRoute = VendorLayoutDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => VendorLayoutRoute,
} as any)
const VendorLayoutProductsRoute = VendorLayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => VendorLayoutRoute,
} as any)
const VendorLayoutProfileRoute = VendorLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => VendorLayoutRoute,
} as any)
const VendorClaimVendorIdRoute = VendorClaimVendorIdRouteImport.update({
  id: '/vendor/claim/$vendorId',
  path: '/vendor/claim/$vendorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/apply/$slug': typeof ApplySlugRoute
  '/market/$slug': typeof MarketSlugRoute
  '/organizer': typeof OrganizerLayoutRouteWithChildren
  '/store/$vendorId': typeof StoreVendorIdRoute
  '/vendor': typeof VendorLayoutRouteWithChildren
  '/admin/organizations': typeof AdminLayoutOrganizationsRoute
  '/organizer/analytics': typeof OrganizerLayoutAnalyticsRoute
  '/organizer/communications': typeof OrganizerLayoutCommunicationsRoute
  '/organizer/compliance': typeof OrganizerLayoutComplianceRoute
  '/organizer/orders': typeof OrganizerLayoutOrdersRoute
  '/organizer/payments': typeof OrganizerLayoutPaymentsRoute
  '/organizer/schedule': typeof OrganizerLayoutScheduleRoute
  '/organizer/settings': typeof OrganizerLayoutSettingsRoute
  '/organizer/vendors': typeof OrganizerLayoutVendorsRoute
  '/vendor/documents': typeof VendorLayoutDocumentsRoute
  '/vendor/products': typeof VendorLayoutProductsRoute
  '/vendor/profile': typeof VendorLayoutProfileRoute
  '/vendor/claim/$vendorId': typeof VendorClaimVendorIdRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/organizer/': typeof OrganizerLayoutIndexRoute
  '/vendor/': typeof VendorLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/apply/$slug': typeof ApplySlugRoute
  '/market/$slug': typeof MarketSlugRoute
  '/store/$vendorId': typeof StoreVendorIdRoute
  '/admin/organizations': typeof AdminLayoutOrganizationsRoute
  '/organizer/analytics': typeof OrganizerLayoutAnalyticsRoute
  '/organizer/communications': typeof OrganizerLayoutCommunicationsRoute
  '/organizer/compliance': typeof OrganizerLayoutComplianceRoute
  '/organizer/orders': typeof OrganizerLayoutOrdersRoute
  '/organizer/payments': typeof OrganizerLayoutPaymentsRoute
  '/organizer/schedule': typeof OrganizerLayoutScheduleRoute
  '/organizer/settings': typeof OrganizerLayoutSettingsRoute
  '/organizer/vendors': typeof OrganizerLayoutVendorsRoute
  '/vendor/documents': typeof VendorLayoutDocumentsRoute
  '/vendor/products': typeof VendorLayoutProductsRoute
  '/vendor/profile': typeof VendorLayoutProfileRoute
  '/vendor/claim/$vendorId': typeof VendorClaimVendorIdRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/organizer': typeof OrganizerLayoutIndexRoute
  '/vendor': typeof VendorLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/apply/$slug': typeof ApplySlugRoute
  '/market/$slug': typeof MarketSlugRoute
  '/organizer/_layout': typeof OrganizerLayoutRouteWithChildren
  '/store/$vendorId': typeof StoreVendorIdRoute
  '/vendor/_layout': typeof VendorLayoutRouteWithChildren
  '/admin/_layout/organizations': typeof AdminLayoutOrganizationsRoute
  '/organizer/_layout/analytics': typeof OrganizerLayoutAnalyticsRoute
  '/organizer/_layout/communications': typeof OrganizerLayoutCommunicationsRoute
  '/organizer/_layout/compliance': typeof OrganizerLayoutComplianceRoute
  '/organizer/_layout/orders': typeof OrganizerLayoutOrdersRoute
  '/organizer/_layout/payments': typeof OrganizerLayoutPaymentsRoute
  '/organizer/_layout/schedule': typeof OrganizerLayoutScheduleRoute
  '/organizer/_layout/settings': typeof OrganizerLayoutSettingsRoute
  '/organizer/_layout/vendors': typeof OrganizerLayoutVendorsRoute
  '/vendor/_layout/documents': typeof VendorLayoutDocumentsRoute
  '/vendor/_layout/products': typeof VendorLayoutProductsRoute
  '/vendor/_layout/profile': typeof VendorLayoutProfileRoute
  '/vendor/claim/$vendorId': typeof VendorClaimVendorIdRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/organizer/_layout/': typeof OrganizerLayoutIndexRoute
  '/vendor/_layout/': typeof VendorLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin'
    | '/apply/$slug'
    | '/market/$slug'
    | '/organizer'
    | '/store/$vendorId'
    | '/vendor'
    | '/admin/organizations'
    | '/organizer/analytics'
    | '/organizer/communications'
    | '/organizer/compliance'
    | '/organizer/orders'
    | '/organizer/payments'
    | '/organizer/schedule'
    | '/organizer/settings'
    | '/organizer/vendors'
    | '/vendor/documents'
    | '/vendor/products'
    | '/vendor/profile'
    | '/vendor/claim/$vendorId'
    | '/admin/'
    | '/organizer/'
    | '/vendor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/apply/$slug'
    | '/market/$slug'
    | '/store/$vendorId'
    | '/admin/organizations'
    | '/organizer/analytics'
    | '/organizer/communications'
    | '/organizer/compliance'
    | '/organizer/orders'
    | '/organizer/payments'
    | '/organizer/schedule'
    | '/organizer/settings'
    | '/organizer/vendors'
    | '/vendor/documents'
    | '/vendor/products'
    | '/vendor/profile'
    | '/vendor/claim/$vendorId'
    | '/admin'
    | '/organizer'
    | '/vendor'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin/_layout'
    | '/apply/$slug'
    | '/market/$slug'
    | '/organizer/_layout'
    | '/store/$vendorId'
    | '/vendor/_layout'
    | '/admin/_layout/organizations'
    | '/organizer/_layout/analytics'
    | '/organizer/_layout/communications'
    | '/organizer/_layout/compliance'
    | '/organizer/_layout/orders'
    | '/organizer/_layout/payments'
    | '/organizer/_layout/schedule'
    | '/organizer/_layout/settings'
    | '/organizer/_layout/vendors'
    | '/vendor/_layout/documents'
    | '/vendor/_layout/products'
    | '/vendor/_layout/profile'
    | '/vendor/claim/$vendorId'
    | '/admin/_layout/'
    | '/organizer/_layout/'
    | '/vendor/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  ApplySlugRoute: typeof ApplySlugRoute
  MarketSlugRoute: typeof MarketSlugRoute
  OrganizerLayoutRoute: typeof OrganizerLayoutRouteWithChildren
  StoreVendorIdRoute: typeof StoreVendorIdRoute
  VendorLayoutRoute: typeof VendorLayoutRouteWithChildren
  VendorClaimVendorIdRoute: typeof VendorClaimVendorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$slug': {
      id: '/apply/$slug'
      path: '/apply/$slug'
      fullPath: '/apply/$slug'
      preLoaderRoute: typeof ApplySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$slug': {
      id: '/market/$slug'
      path: '/market/$slug'
      fullPath: '/market/$slug'
      preLoaderRoute: typeof MarketSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/_layout': {
      id: '/organizer/_layout'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$vendorId': {
      id: '/store/$vendorId'
      path: '/store/$vendorId'
      fullPath: '/store/$vendorId'
      preLoaderRoute: typeof StoreVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/_layout': {
      id: '/vendor/_layout'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/organizations': {
      id: '/admin/_layout/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminLayoutOrganizationsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/organizer/_layout/': {
      id: '/organizer/_layout/'
      path: '/'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerLayoutIndexRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/organizer/_layout/analytics': {
      id: '/organizer/_layout/analytics'
      path: '/analytics'
      fullPath: '/organizer/analytics'
      preLoaderRoute: typeof OrganizerLayoutAnalyticsRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/organizer/_layout/communications': {
      id: '/organizer/_layout/communications'
      path: '/communications'
      fullPath: '/organizer/communications'
      preLoaderRoute: typeof OrganizerLayoutCommunicationsRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/organizer/_layout/compliance': {
      id: '/organizer/_layout/compliance'
      path: '/compliance'
      fullPath: '/organizer/compliance'
      preLoaderRoute: typeof OrganizerLayoutComplianceRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/organizer/_layout/orders': {
      id: '/organizer/_layout/orders'
      path: '/orders'
      fullPath: '/organizer/orders'
      preLoaderRoute: typeof OrganizerLayoutOrdersRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/organizer/_layout/payments': {
      id: '/organizer/_layout/payments'
      path: '/payments'
      fullPath: '/organizer/payments'
      preLoaderRoute: typeof OrganizerLayoutPaymentsRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/organizer/_layout/schedule': {
      id: '/organizer/_layout/schedule'
      path: '/schedule'
      fullPath: '/organizer/schedule'
      preLoaderRoute: typeof OrganizerLayoutScheduleRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/organizer/_layout/settings': {
      id: '/organizer/_layout/settings'
      path: '/settings'
      fullPath: '/organizer/settings'
      preLoaderRoute: typeof OrganizerLayoutSettingsRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/organizer/_layout/vendors': {
      id: '/organizer/_layout/vendors'
      path: '/vendors'
      fullPath: '/organizer/vendors'
      preLoaderRoute: typeof OrganizerLayoutVendorsRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/vendor/_layout/': {
      id: '/vendor/_layout/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorLayoutIndexRouteImport
      parentRoute: typeof VendorLayoutRoute
    }
    '/vendor/_layout/documents': {
      id: '/vendor/_layout/documents'
      path: '/documents'
      fullPath: '/vendor/documents'
      preLoaderRoute: typeof VendorLayoutDocumentsRouteImport
      parentRoute: typeof VendorLayoutRoute
    }
    '/vendor/_layout/products': {
      id: '/vendor/_layout/products'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof VendorLayoutProductsRouteImport
      parentRoute: typeof VendorLayoutRoute
    }
    '/vendor/_layout/profile': {
      id: '/vendor/_layout/profile'
      path: '/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof VendorLayoutProfileRouteImport
      parentRoute: typeof VendorLayoutRoute
    }
    '/vendor/claim/$vendorId': {
      id: '/vendor/claim/$vendorId'
      path: '/vendor/claim/$vendorId'
      fullPath: '/vendor/claim/$vendorId'
      preLoaderRoute: typeof VendorClaimVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutOrganizationsRoute: typeof AdminLayoutOrganizationsRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutOrganizationsRoute: AdminLayoutOrganizationsRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface OrganizerLayoutRouteChildren {
  OrganizerLayoutAnalyticsRoute: typeof OrganizerLayoutAnalyticsRoute
  OrganizerLayoutCommunicationsRoute: typeof OrganizerLayoutCommunicationsRoute
  OrganizerLayoutComplianceRoute: typeof OrganizerLayoutComplianceRoute
  OrganizerLayoutOrdersRoute: typeof OrganizerLayoutOrdersRoute
  OrganizerLayoutPaymentsRoute: typeof OrganizerLayoutPaymentsRoute
  OrganizerLayoutScheduleRoute: typeof OrganizerLayoutScheduleRoute
  OrganizerLayoutSettingsRoute: typeof OrganizerLayoutSettingsRoute
  OrganizerLayoutVendorsRoute: typeof OrganizerLayoutVendorsRoute
  OrganizerLayoutIndexRoute: typeof OrganizerLayoutIndexRoute
}

const OrganizerLayoutRouteChildren: OrganizerLayoutRouteChildren = {
  OrganizerLayoutAnalyticsRoute: OrganizerLayoutAnalyticsRoute,
  OrganizerLayoutCommunicationsRoute: OrganizerLayoutCommunicationsRoute,
  OrganizerLayoutComplianceRoute: OrganizerLayoutComplianceRoute,
  OrganizerLayoutOrdersRoute: OrganizerLayoutOrdersRoute,
  OrganizerLayoutPaymentsRoute: OrganizerLayoutPaymentsRoute,
  OrganizerLayoutScheduleRoute: OrganizerLayoutScheduleRoute,
  OrganizerLayoutSettingsRoute: OrganizerLayoutSettingsRoute,
  OrganizerLayoutVendorsRoute: OrganizerLayoutVendorsRoute,
  OrganizerLayoutIndexRoute: OrganizerLayoutIndexRoute,
}

const OrganizerLayoutRouteWithChildren = OrganizerLayoutRoute._addFileChildren(
  OrganizerLayoutRouteChildren,
)

interface VendorLayoutRouteChildren {
  VendorLayoutDocumentsRoute: typeof VendorLayoutDocumentsRoute
  VendorLayoutProductsRoute: typeof VendorLayoutProductsRoute
  VendorLayoutProfileRoute: typeof VendorLayoutProfileRoute
  VendorLayoutIndexRoute: typeof VendorLayoutIndexRoute
}

const VendorLayoutRouteChildren: VendorLayoutRouteChildren = {
  VendorLayoutDocumentsRoute: VendorLayoutDocumentsRoute,
  VendorLayoutProductsRoute: VendorLayoutProductsRoute,
  VendorLayoutProfileRoute: VendorLayoutProfileRoute,
  VendorLayoutIndexRoute: VendorLayoutIndexRoute,
}

const VendorLayoutRouteWithChildren = VendorLayoutRoute._addFileChildren(
  VendorLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  ApplySlugRoute: ApplySlugRoute,
  MarketSlugRoute: MarketSlugRoute,
  OrganizerLayoutRoute: OrganizerLayoutRouteWithChildren,
  StoreVendorIdRoute: StoreVendorIdRoute,
  VendorLayoutRoute: VendorLayoutRouteWithChildren,
  VendorClaimVendorIdRoute: VendorClaimVendorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
