/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrganizerLayoutRouteImport } from './routes/organizer/_layout'
import { Route as OrganizerLayoutIndexRouteImport } from './routes/organizer/_layout/index'
import { Route as OrganizerLayoutAnalyticsRouteImport } from './routes/organizer/_layout/analytics'
import { Route as OrganizerLayoutCommunicationsRouteImport } from './routes/organizer/_layout/communications'
import { Route as OrganizerLayoutComplianceRouteImport } from './routes/organizer/_layout/compliance'
import { Route as OrganizerLayoutOrdersRouteImport } from './routes/organizer/_layout/orders'
import { Route as OrganizerLayoutPaymentsRouteImport } from './routes/organizer/_layout/payments'
import { Route as OrganizerLayoutScheduleRouteImport } from './routes/organizer/_layout/schedule'
import { Route as OrganizerLayoutSettingsRouteImport } from './routes/organizer/_layout/settings'
import { Route as OrganizerLayoutVendorsRouteImport } from './routes/organizer/_layout/vendors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerLayoutRoute = OrganizerLayoutRouteImport.update({
  id: '/organizer/_layout',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerLayoutIndexRoute = OrganizerLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizerLayoutRoute,
} as any)
const OrganizerLayoutAnalyticsRoute =
  OrganizerLayoutAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => OrganizerLayoutRoute,
  } as any)
const OrganizerLayoutCommunicationsRoute =
  OrganizerLayoutCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => OrganizerLayoutRoute,
  } as any)
const OrganizerLayoutComplianceRoute =
  OrganizerLayoutComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => OrganizerLayoutRoute,
  } as any)
const OrganizerLayoutOrdersRoute = OrganizerLayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => OrganizerLayoutRoute,
} as any)
const OrganizerLayoutPaymentsRoute = OrganizerLayoutPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => OrganizerLayoutRoute,
} as any)
const OrganizerLayoutScheduleRoute = OrganizerLayoutScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => OrganizerLayoutRoute,
} as any)
const OrganizerLayoutSettingsRoute = OrganizerLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrganizerLayoutRoute,
} as any)
const OrganizerLayoutVendorsRoute = OrganizerLayoutVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => OrganizerLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/organizer': typeof OrganizerLayoutRouteWithChildren
  '/organizer/analytics': typeof OrganizerLayoutAnalyticsRoute
  '/organizer/communications': typeof OrganizerLayoutCommunicationsRoute
  '/organizer/compliance': typeof OrganizerLayoutComplianceRoute
  '/organizer/orders': typeof OrganizerLayoutOrdersRoute
  '/organizer/payments': typeof OrganizerLayoutPaymentsRoute
  '/organizer/schedule': typeof OrganizerLayoutScheduleRoute
  '/organizer/settings': typeof OrganizerLayoutSettingsRoute
  '/organizer/vendors': typeof OrganizerLayoutVendorsRoute
  '/organizer/': typeof OrganizerLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/organizer/analytics': typeof OrganizerLayoutAnalyticsRoute
  '/organizer/communications': typeof OrganizerLayoutCommunicationsRoute
  '/organizer/compliance': typeof OrganizerLayoutComplianceRoute
  '/organizer/orders': typeof OrganizerLayoutOrdersRoute
  '/organizer/payments': typeof OrganizerLayoutPaymentsRoute
  '/organizer/schedule': typeof OrganizerLayoutScheduleRoute
  '/organizer/settings': typeof OrganizerLayoutSettingsRoute
  '/organizer/vendors': typeof OrganizerLayoutVendorsRoute
  '/organizer': typeof OrganizerLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/organizer/_layout': typeof OrganizerLayoutRouteWithChildren
  '/organizer/_layout/analytics': typeof OrganizerLayoutAnalyticsRoute
  '/organizer/_layout/communications': typeof OrganizerLayoutCommunicationsRoute
  '/organizer/_layout/compliance': typeof OrganizerLayoutComplianceRoute
  '/organizer/_layout/orders': typeof OrganizerLayoutOrdersRoute
  '/organizer/_layout/payments': typeof OrganizerLayoutPaymentsRoute
  '/organizer/_layout/schedule': typeof OrganizerLayoutScheduleRoute
  '/organizer/_layout/settings': typeof OrganizerLayoutSettingsRoute
  '/organizer/_layout/vendors': typeof OrganizerLayoutVendorsRoute
  '/organizer/_layout/': typeof OrganizerLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/organizer'
    | '/organizer/analytics'
    | '/organizer/communications'
    | '/organizer/compliance'
    | '/organizer/orders'
    | '/organizer/payments'
    | '/organizer/schedule'
    | '/organizer/settings'
    | '/organizer/vendors'
    | '/organizer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/organizer/analytics'
    | '/organizer/communications'
    | '/organizer/compliance'
    | '/organizer/orders'
    | '/organizer/payments'
    | '/organizer/schedule'
    | '/organizer/settings'
    | '/organizer/vendors'
    | '/organizer'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/organizer/_layout'
    | '/organizer/_layout/analytics'
    | '/organizer/_layout/communications'
    | '/organizer/_layout/compliance'
    | '/organizer/_layout/orders'
    | '/organizer/_layout/payments'
    | '/organizer/_layout/schedule'
    | '/organizer/_layout/settings'
    | '/organizer/_layout/vendors'
    | '/organizer/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OrganizerLayoutRoute: typeof OrganizerLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/_layout': {
      id: '/organizer/_layout'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/_layout/': {
      id: '/organizer/_layout/'
      path: '/'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerLayoutIndexRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/organizer/_layout/analytics': {
      id: '/organizer/_layout/analytics'
      path: '/analytics'
      fullPath: '/organizer/analytics'
      preLoaderRoute: typeof OrganizerLayoutAnalyticsRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/organizer/_layout/communications': {
      id: '/organizer/_layout/communications'
      path: '/communications'
      fullPath: '/organizer/communications'
      preLoaderRoute: typeof OrganizerLayoutCommunicationsRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/organizer/_layout/compliance': {
      id: '/organizer/_layout/compliance'
      path: '/compliance'
      fullPath: '/organizer/compliance'
      preLoaderRoute: typeof OrganizerLayoutComplianceRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/organizer/_layout/orders': {
      id: '/organizer/_layout/orders'
      path: '/orders'
      fullPath: '/organizer/orders'
      preLoaderRoute: typeof OrganizerLayoutOrdersRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/organizer/_layout/payments': {
      id: '/organizer/_layout/payments'
      path: '/payments'
      fullPath: '/organizer/payments'
      preLoaderRoute: typeof OrganizerLayoutPaymentsRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/organizer/_layout/schedule': {
      id: '/organizer/_layout/schedule'
      path: '/schedule'
      fullPath: '/organizer/schedule'
      preLoaderRoute: typeof OrganizerLayoutScheduleRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/organizer/_layout/settings': {
      id: '/organizer/_layout/settings'
      path: '/settings'
      fullPath: '/organizer/settings'
      preLoaderRoute: typeof OrganizerLayoutSettingsRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/organizer/_layout/vendors': {
      id: '/organizer/_layout/vendors'
      path: '/vendors'
      fullPath: '/organizer/vendors'
      preLoaderRoute: typeof OrganizerLayoutVendorsRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
  }
}

interface OrganizerLayoutRouteChildren {
  OrganizerLayoutAnalyticsRoute: typeof OrganizerLayoutAnalyticsRoute
  OrganizerLayoutCommunicationsRoute: typeof OrganizerLayoutCommunicationsRoute
  OrganizerLayoutComplianceRoute: typeof OrganizerLayoutComplianceRoute
  OrganizerLayoutOrdersRoute: typeof OrganizerLayoutOrdersRoute
  OrganizerLayoutPaymentsRoute: typeof OrganizerLayoutPaymentsRoute
  OrganizerLayoutScheduleRoute: typeof OrganizerLayoutScheduleRoute
  OrganizerLayoutSettingsRoute: typeof OrganizerLayoutSettingsRoute
  OrganizerLayoutVendorsRoute: typeof OrganizerLayoutVendorsRoute
  OrganizerLayoutIndexRoute: typeof OrganizerLayoutIndexRoute
}

const OrganizerLayoutRouteChildren: OrganizerLayoutRouteChildren = {
  OrganizerLayoutAnalyticsRoute: OrganizerLayoutAnalyticsRoute,
  OrganizerLayoutCommunicationsRoute: OrganizerLayoutCommunicationsRoute,
  OrganizerLayoutComplianceRoute: OrganizerLayoutComplianceRoute,
  OrganizerLayoutOrdersRoute: OrganizerLayoutOrdersRoute,
  OrganizerLayoutPaymentsRoute: OrganizerLayoutPaymentsRoute,
  OrganizerLayoutScheduleRoute: OrganizerLayoutScheduleRoute,
  OrganizerLayoutSettingsRoute: OrganizerLayoutSettingsRoute,
  OrganizerLayoutVendorsRoute: OrganizerLayoutVendorsRoute,
  OrganizerLayoutIndexRoute: OrganizerLayoutIndexRoute,
}

const OrganizerLayoutRouteWithChildren = OrganizerLayoutRoute._addFileChildren(
  OrganizerLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OrganizerLayoutRoute: OrganizerLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
